### ISSUE TITLE
Missing BuildConfig

### ISSUE THREAD

**Issue by faust64** [marrober/signature-repo#1]
Hi,

Cloud you clarify: what's in your signature-server BuildConfig?

AFAIU, it's mentionned here https://github.com/marrober/signature-repo/blob/92733a8b15295066e845acec2c4a240bfbde1f29/automation/triggers/triggerTemplate.yaml#L21 and there https://github.com/marrober/signature-repo/blob/92733a8b15295066e845acec2c4a240bfbde1f29/automation/pipeline/pipelineRun.yaml#L13
The dockerfile (https://github.com/marrober/signature-repo/blob/92733a8b15295066e845acec2c4a240bfbde1f29/test/dockerfile) doesn't look like what I'm looking for

How does this work?

As a sidenote: why would you use Tekton Pipelines & Tekton Triggers? AFAIU, adding a trigger to your BuildConfig should be enough to receive notifications and start new jobs. Or go full Tekton, not using BuildConfigs may simplify integration into "regular" k8s.

**Comment by marrober** [comment]
The signature server build config is created by OpenShift when the httpd server is created. This is taken straight off the OpenShift catalog and there is no configuration appliled. The start-build process simply forces the httpd server to refresh the content that it is serving from the github store that hold the signatures.

You are right that the Tekton process is not entirely necessary and could be done by triggering the build config from a webhook on GitHub.
